
title: Hakan Bayır
title2 : Hakan Bayır
title3 : 2017 - 2018
whois : "| Cyber Struggle Ranger |"
#title_english: English

email: hakannnbayir@gmail.com

description:  Siber güvenlik ve bilişim teknolojileri üzerine içerik üretilen kişisel bir blog.

baseurl: "" 
baseurl2: ""

url: "" 


markdown: kramdown
